name: react

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t mariam-sn/react-app -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true mariam-sn/react-app npm run test

# commenttttdddmmmmnnnmm
